#!/usr/bin/env python3
import re
import os
import sys
import requests
from bs4 import BeautifulSoup


def url_generater(path):
    song = os.path.realpath(path).split('/')

    name = os.path.splitext(song[-1])[0]
    name = re.sub(r'\(.+?\)', '', name)
    name = ''.join(re.findall(r'\w', name)).lower()


    artist = song[5].lower().replace(' ', '')
    return 'http://www.azlyrics.com/lyrics/{}/{}.html'.format(artist, name)


def searching(keyword):
    url = 'http://search.azlyrics.com/search.php?q='

    r = requests.get(url+keyword, headers=headers)
    soup = BeautifulSoup(r.text, "html.parser")

    return soup.find_all('tbody')[-1].find('td').find('a').get('href')


headers = {'user-agent': 'Mozilla/5.0 (X11 Linux x86_64) AppleWebKit/537.36 '
           '(KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36'}

r = requests.get(url_generater(sys.argv[1]), headers=headers)

if r.status_code == 404:
    keyword = os.path.splitext(sys.argv[1])[0].replace(' ', '+')
    lyrics_url = searching(keyword)

    r = requests.get(lyrics_url, headers=headers)

soup = BeautifulSoup(r.text, "html.parser")
print(soup.find('span', {'id': 'cf_text_top'}).find_next('div').text.strip())
